language: rust
rust:
  - nightly
before_install:
  - sudo apt-get update
  - sudo apt-get -y install qemu
before_script:
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - cargo install bootimage
script:
  - cargo bootimage --verbose
  - cargo test --verbose